views/account.py
from flask import Blueprint, redirect, request, render_template, url_for, flash
from flask import Blueprint, render_template, flash, redirect, url_for,current_app, session
from auth.forms import PersonalDetailsForm, AddEmailForm, AddPhoneForm, AddBankForm
from sql.db import DB

from flask_login import login_user, login_required, logout_user, current_user
from auth.models import User
from sql.db import DB
account = Blueprint('account', __name__, url_prefix='/account')


@account.route('/modify', methods=['GET', 'POST'])
@login_required
def modify():
    user_id = current_user.get_id()
    user_email = current_user.get_email()

    form = PersonalDetailsForm()
    print("ssnnnnnnn")
    if request.method == "POST":
        data = {} # use this as needed, can convert to tuple if necessary
            # TODO edit-1 retrieve form data for name, address, city, state, country, zip, website
        name = request.form.get("name")
        email = request.form.get("email")
        ssn= request.form.get("ssn")
        phone = request.form.get("phone")
        password = request.form.get("password")
        result= DB.selectOne("SELECT * FROM EMAIL NATURAL JOIN USER_ACCOUNT WHERE EMAIL_ADD = %s" ,user_email)
        try:
            
            if(ssn):
                upssn= DB.update("UPDATE USER_ACCOUNT SET SSN=%s WHERE SSN= %s",ssn, result.row["SSN"])
                flash("Updation Successful", "success")
        except Exception as e :
            flash(f"Error updating value {e}","danger")
        # handle password change only if all 3 are provided
        if password:
            try:
                result = DB.selectOne("SELECT password FROM USER_LOGIN where id = %s", user_id)
                print(result)
                if result.status and result.row:
                    # verify current password
                    if (result.row["password"]):
                        # update new password
                        hash = password
                        try:
                            result = DB.update("UPDATE USER_LOGIN SET password = %s WHERE id = %s", hash, user_id)
                            if result.status:
                                flash("Updated password", "success")
                        except Exception as ue:
                            flash(f"Failed to update password : {ue}", "danger")
                    else:
                        flash("Invalid password","danger")
            except Exception as se:
                flash(f"Password could not be retrieved : {se}", "danger")
        
        if email:
            try: # update email, username (this will trigger if nothing changed but it's fine)
                result0 = DB.update("UPDATE ELEC_ADDRESS SET IDENTIFIER = %s WHERE IDENTIFIER = %s", email, user_email)
                #result = DB.update("UPDATE USER_LOGIN SET EMAIL = %s WHERE id = %s", email, user_id)
                if result0.status:
                    flash("Saved profile", "success")
            except Exception as e:
                flash(f"Error! Failed to update the profile because {e}", "danger")
                
        if name:
            try: # update email, username (this will trigger if nothing changed but it's fine)
                result0 = DB.update("UPDATE USER_ACCOUNT SET NAME = %s WHERE SSN = %s", name, result.row["SSN"])
                #result = DB.update("UPDATE USER_LOGIN SET EMAIL = %s WHERE id = %s", email, user_id)
                if result0.status:
                    flash("Saved profile", "success")
            except Exception as e:
                flash(f"Error! Failed to update the profile because {e}", "danger")
                
    try:
        # get latest info if anything changed
        res_amt = DB.selectAll("Select * FROM EMAIL NATURAL JOIN USER_ACCOUNT WHERE EMAIL_ADD=%s ",user_email)
        #result_1= DB.selectAll("SELECT * FROM USER_ACCOUNT WHERE SSN = %s", res_amt.row["SSN"])
        print("------------------")
        print(res_amt.row)
        if res_amt.status and res_amt.row:
            print("------------------")
            print(res_amt.row)
            user = res_amt.row
            form = PersonalDetailsForm(obj=user)
            # TODO update session
            current_user.email = user.email
            #current_user.name = user.name
            session["user"] = current_user.toJson()
    except Exception as e:
        flash("Failed to retrieve updated info", "danger")
    
    row = {}
    try:
        # TODO edit-11 fetch the updated data
        print(user_email)
        res_amt = DB.selectOne("Select SSN FROM EMAIL NATURAL JOIN USER_ACCOUNT WHERE EMAIL_ADD=%s ",user_email)
        print(res_amt.row)
        result = DB.selectOne("SELECT SSN, NAME, PHONE_NUMBER FROM USER_ACCOUNT WHERE SSN=%s", res_amt.row["SSN"])
        if result.status:
            row = result.row
            flash("Successfully Updated","success")
    except Exception as e:
        # TODO edit-12 make this user-friendly
        flash("Error occured! The data cannot be retrived", "danger")
# TODO edit-13 pass the company data to the render template
    return render_template("personal_details.html", account=row)


    
@account.route('/email', methods=['GET', 'POST'])
@login_required
def email():
    user_id = current_user.get_id()
    user_email = current_user.get_email()

    res_amt = DB.selectOne("Select SSN FROM EMAIL NATURAL JOIN USER_ACCOUNT WHERE EMAIL_ADD=%s ",user_email)
    #flash(f"ID IS {user_id}","success")
    form = AddEmailForm()
    if form.validate_on_submit():
        email = form.email.data
        try:
            try:
                result=DB.insertOne("INSERT INTO ELEC_ADDRESS(IDENTIFIER,type_eorp) VALUES (%s,'email')",email)
                add_email= DB.insertOne("INSERT INTO EMAIL(EMAIL_ADD, SSN) VALUES (%s,%s)",email,res_amt.row["SSN"])
                if add_email.status:
                    flash("Successfully inserted new email", "success")
            except Exception as e:
                    flash(f"Error! Failed to add email because {e}", "danger")
        except Exception as e:
                flash(f"Error! Failed to get email data {e}", "danger")
    try:
        res=DB.selectAll("SELECT EMAIL_ADD FROM EMAIL WHERE SSN=%s",res_amt.row["SSN"])
    except Exception as e:
        flash(f"Error collecting emails {e}","danger")

    return render_template("add_email.html",form=form,resp=res)

@account.route("/delete_email", methods=["GET"])
def delete_email():
    user_email = current_user.get_email()
    email = request.args.get("ids")
    # make a mutable dict
    args = {**request.args}
    print(user_email)
    print(email)
    if(user_email!=email):
        try:
            result = DB.delete("DELETE FROM ELEC_ADDRESS WHERE IDENTIFIER = %s", email)
            if result.status:
                flash("Deleted record", "success")
        except Exception as e:
            # TODO make this user-friendly
            flash("Error! Failed to Delete records", "danger")
        # TODO pass along feedback

        # remove the id args since we don't need it in the list route
        # but we want to persist the other query args
        del args["ids"]
    return redirect(url_for("account.email", **args))

@account.route("/delete_phone", methods=["GET"])
def delete_phone():
    user_email=current_user.email
    phone = request.args.get("ids")
    # make a mutable dict
    args = {**request.args}
    print(phone)
    try:
        result = DB.delete("DELETE FROM ELEC_ADDRESS WHERE IDENTIFIER = %s", phone)
        if result.status:
            flash("Deleted record", "success")
    except Exception as e:
        # TODO make this user-friendly
        flash("Error! Failed to Delete records", "danger")
    # TODO pass along feedback

    # remove the id args since we don't need it in the list route
    # but we want to persist the other query args
    del args["ids"]
    return redirect(url_for("account.phone", **args))

@account.route('/phone', methods=['GET', 'POST'])
@login_required
def phone():
    user_email = current_user.get_email()
    form = AddPhoneForm()
    res={}
    res_amt = DB.selectOne("Select SSN FROM EMAIL NATURAL JOIN USER_ACCOUNT WHERE EMAIL_ADD=%s ",user_email)
    if form.validate_on_submit():
        phone = form.phone.data
        #res_amt = DB.selectOne("Select SSN, NAME, BALANCE FROM EMAIL NATURAL JOIN USER_ACCOUNT WHERE EMAIL_ADD=%s ",user_email)
        try:
            result=DB.insertOne("INSERT INTO ELEC_ADDRESS(IDENTIFIER,type_eorp) VALUES (%s,'phone')",phone)
            add_phone= DB.insertOne("INSERT INTO PHONE(PHONE_NO, SSN) VALUES (%s,%s)",phone,res_amt.row["SSN"])
            #add_phone= DB.insertOne("INSERT INTO USER_ACCOUNT(SSN, NAME, PHONE_NUMBER, BALANCE) VALUES (%s,%s,%s,%s)",res_amt.row["SSN"],res_amt.row["NAME"],phone,res_amt.row["BALANCE"])
                
            if result.status:
                flash("Successfully inserted new phone", "success")
        except Exception as e:
                flash(f"Error! Failed to add the phone because {e}", "danger")
    try:
        res=DB.selectAll("SELECT PHONE_NO FROM PHONE WHERE SSN=%s ",res_amt.row["SSN"])
    except Exception as e:
        flash(f"Error collecting phone {e}","danger")
    return render_template("add_phone.html",form=form,resp=res)


@account.route('/bank', methods=['GET', 'POST'])
@login_required
def bank():
    user_id = current_user.get_id()
    user_email = current_user.get_email()
    form = AddBankForm()

    res_amt = DB.selectOne("Select SSN FROM EMAIL NATURAL JOIN USER_ACCOUNT WHERE EMAIL_ADD=%s ",user_email)
    if form.validate_on_submit():
        bankid = form.bankid.data
        bank = form.bank.data
        try:
            try:
                result=DB.insertOne("INSERT INTO BANK_ACCOUNT(BANK_ID,BANK_NUMBER) VALUES (%s,%s)",bankid,bank)
                result=DB.insertOne("INSERT INTO HAS_ADDITIONAL(SSN,BANK_ID,BANK_NUMBER) VALUES (%s,%s,%s)",res_amt.row["SSN"],bankid,bank)

views/sample.py
from flask import Blueprint, redirect, request, render_template, url_for, flash
from flask import Blueprint, render_template, flash, redirect, url_for,current_app, session
from auth.forms import LoginForm, RegisterForm
from sql.db import DB

from flask_login import login_user, login_required, logout_user, current_user
from sql.db import DB
sample = Blueprint('sample', __name__, url_prefix='/sample')

sample.route('/account_info', methods=['GET', 'POST'])
def account_info():
    user_id = current_user.get_id()
    flash("ID IS ","success")
    '''k = request.form.get("key", None)
    v = request.form.get("value", None)
    if k and v:
        try:
            result = DB.insertOne(
                "INSERT INTO IS601_Sample (name, val) VALUES(%s, %s)", k, v)
            if result.status:
                flash("Created Record", "success")
        except Exception as e:
            # TODO make this user-friendly
            flash("Error! Record cannot be created", "danger")'''

    return render_template("account_info.html")
@sample.route('/add', methods=['GET', 'POST'])
def add():
    k = request.form.get("key", None)
    v = request.form.get("value", None)
    if k and v:
        try:
            result = DB.insertOne(
                "INSERT INTO IS601_Sample (name, val) VALUES(%s, %s)", k, v)
            if result.status:
                flash("Created Record", "success")
        except Exception as e:
            # TODO make this user-friendly
            flash("Error! Record cannot be created", "danger")

    return render_template("add_sample.html")

@sample.route('/list', methods=['GET'])
def list():
    key = request.args.get("name")
    col = request.args.get("col")
    order = request.args.get("order")
    limit = request.args.get("limit", 10)
    args = []
    print(f"col {col} order {order}")
    # dynamically build our query and data mappings
    # use the WHERE true trick so we can easily append conditions without caring if a condition
    # already was applied (no need to check if WHERE exists)
    query = "SELECT id, name, val, created, modified from IS601_Sample WHERE 1=1"
    if key:
        query += " AND name like %s"
        args.append(f"%{key}%")
    if col and order:
        # incorrect
        # these get passed as safe strings rather than sql keywords
        # query += f" ORDER BY %s %s"
        # args.append(col)
        # args.append(order)
        # correct - validate fully that col and order are expected values
        # this will be directly injected and if not validated could
        # lead to sql injection
        if col in ["name","val","created","modified"] \
            and order in ["asc", "desc"]:
            query += f" ORDER BY {col} {order}"

    if limit and int(limit) > 0 and int(limit) <= 100:
        # technically this should follow the same rules as col/order
        # but it seems to work with the placeholder mapping with
        # this connector
        query += " LIMIT %s"
        args.append(int(limit))
    rows = []
    try:
        # convert our list to args via *
        print(query)
        resp = DB.selectAll(query, *args)
        if resp.status:
            rows = resp.rows
    except Exception as e:
        # TODO make this user-friendly
        flash("Error! Failed to list the records", "danger")
    
    return render_template("list_sample.html", resp=rows)

@sample.route("/edit", methods=["GET", "POST"])
def edit():
    id = request.args.get("id")
    row = None
    if id is None:
        flash("ID is missing", "danger")
        return redirect("sample.list")
    else:
        if request.method == "POST" and request.form.get("value"):
            val = request.form.get("value")
            try:
                result = DB.update("UPDATE IS601_Sample SET val = %s WHERE id = %s", val, id)
                if result.status:
                    flash("Updated record", "success")
            except Exception as e:
                # TODO make this user-friendly
                flash("Error! Record cannot be updated", "danger")
        try:
            result = DB.selectOne("SELECT name, val FROM IS601_Sample WHERE id = %s", id)
            if result.status:
                row = result.row
        except Exception as e:
            # TODO make this user-friendly
            flash("Error! Failed to list records", "danger")
    return render_template("edit_sample.html", row=row)

@sample.route("/delete", methods=["GET"])
def delete():
    id = request.args.get("id")
    # make a mutable dict
    args = {**request.args}
    if id:
        try:
            result = DB.delete("DELETE FROM IS601_Sample WHERE id = %s", id)
            if result.status:
                flash("Deleted record", "success")
        except Exception as e:
            # TODO make this user-friendly
            flash("Error! Failed to Delete records", "danger")
        # TODO pass along feedback

        # remove the id args since we don't need it in the list route
        # but we want to persist the other query args
        del args["id"]
    return redirect(url_for("sample.list", **args))

templates/_dropdown_nav.html
{% macro dropdown_nav(name, links) %}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
        aria-expanded="false">
        {{name}}
    </a>
    <ul class="dropdown-menu">
        {% for url, text in links %}
        <!-- assumes url is a route and text is a string-->
        <li><a class="dropdown-item" href="{{url_for(url)}}">{{text}}</a></li>
        {% endfor %}
    </ul>
</li>
{% endmacro %}

templates/account_info.html
{% extends "layout.html" %}
{% block title %}Account Details{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Account Details</div>
    <form class="row row-cols-lg-auto g-3 align-items-center">
    </form>
    <table class="table">
        {% if info %}
        <thead>
        <thead>
            <tr class="text-capitalize">
                <th>SSN</th>
                <th>NAME</th>  
                <th>BALANCE</th>
            </tr>
            
        </thead>
        
        <tr>
            <td>{{info["SSN"]}}</td>
            <td>{{info["NAME"]}}</td>
            <td>{{info["BALANCE"]}}</td>
            <br>
            
        </tr>
        </thead>
        
        {% else %}
        <p>No results to show</p>
        {% endif %}
    </table>
    <table class="table">
        {% if resp %}
        <thead>
        <thead>
            <tr class="text-capitalize">
                <th>BANK_ID</th>
                <th>BANK_NUMBER</th>
            </tr>
            
        </thead>
        
        <tr>
            {%for k in resp["rows"] %}
            <td>{{k["BANK_ID"]}}</td>
            <td>{{k["BANK_NUMBER"]}}</td>
            <br>
            
        </tr>
        {% endfor %}
        </thead>
        
        {% else %}
        <p>No results to show</p>
        {% endif %}
    </table>
</div>
</div>
{% endblock %}

templates/add_email.html
{% extends "layout.html" %}
{% block title %}Email{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="container-fluid">
    <div class="h3">Add Email</div>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{render_field(form.email)}}
        {{form.submit(class="btn btn-primary")}}
    </form>
    <table class="table">
        {% if resp %}
        <thead>
        <thead>
            <tr class="text-capitalize">
                <th>ALL PRESENT EMAIL IDs</th>
                
            </tr>
            
        </thead>
    <tbody>
        {%for k in resp["rows"] %}
        <tr>
            <td>{{k["EMAIL_ADD"]}}</td>
            {% if k["EMAIL_ADD"] != current_user.email %}
            <td>
                <a href="{{url_for('account.delete_email', ids=k.get('EMAIL_ADD'), **request.args)}}"
                    class="btn btn-danger btn-sm">x</a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
        </thead>
        
        {% else %}
        <p>No results to show</p>
        {% endif %}
    </table>
</div>

{% endblock %}

templates/add_sample.html
{% extends "layout.html" %}
{% block title %}Add Sample{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Add Sample</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Key</label>
                <input class="form-control" id="n" name="key" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="v">Value</label>
                <input class="form-control" id="v" name="value" />
            </div>
            <input type="submit" class="btn btn-primary" value="Save Sample" />
        </form>
    </div>
</div>
{% endblock %}

templates/edit_sample.html
{% extends "layout.html" %}
{% block title %}Add Sample{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">Edit Sample</div>
    <div>
        <form method="POST">
            <div class="form-group mb-3">
                <label class="form-label" for="n">Key</label>
                <input class="form-control" id="n" name="key" readonly value="{{row.name}}" />
            </div>
            <div class="form-group mb-3">
                <label class="form-label" for="v">Value</label>
                <input class="form-control" id="v" name="value" value="{{row.val}}" />
            </div>
            <input type="submit" class="btn btn-primary" value="Update Sample" />
        </form>
    </div>
</div>
{% endblock %}

templates/layout.html
<!doctype html>
<html>

<head>
    {% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <style>
        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 60px;
            line-height: 60px;
        }

        .header {
            top: 0;
            height: 60px;
            line-height: 60px;
        }
    </style>
    <title>{% block title %}{% endblock %} - DMSD FINAL PROJECT  </title>
    {% endblock %}
</head>

<body>
    <div id="header">
        {% include 'nav.html' %}
        {% include 'flash.html' %}
        <style>
            label {
                text-transform: capitalize;
            }
        </style>
    </div>
    <div id="content">{% block content %}{% endblock %}</div>
    
</body>

</html>

templates/list_sample.html
{% extends "layout.html" %}
{% block title %}List Samples{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1">List Samples</div>
    <form class="row row-cols-lg-auto g-3 align-items-center">
        <div class="col-12">
            <label class="form-label" for="name">Name/Key</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="name/key"
                value="{{request.args.get('name') or ''}}">
        </div>
        <div class="col-12">
            {% set options = ["name", "val", "modified", "created"] %}
            <label class="form-label" for="col">Column</label>
            {# notice value doesn't work for server-side built selects
            that's because the value is set before the options exist so it doesn't pick the proper
            option, instead we need to manually select the correct option or use a JS hack #}
            <select class="form-select" id="col" name="col" value="{{request.args.get('col')}}">
                <option value="">Choose...</option>
                {% for op in options %}
                {# using an inline if to output the selected attribute if it matches the op #}
                <option {{'selected' if request.args.get('col')==op }} value="{{op}}">
                    {{op|capitalize}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-12">
            <label class="form-label" for="order">Order</label>
            <select class="form-select" id="order" name="order" value="{{request.args.get('order')}}">
                <option value="">Choose...</option>
                <option {{'selected' if request.args.get('order')=="asc" }} value="asc">+</option>
                <option {{'selected' if request.args.get('order')=="desc" }} value="desc">-</option>
            </select>
        </div>
        <div class="col-12">
            <label class="form-label" for="limit">Limit</label>
            <input class="form-control" type="number" min="1" max="100" id="limit" name="limit"
                value="{{request.args.get('limit') or '10'}}" />
        </div>
        <div class="col-12">
            <!-- hack to align button with inputs in inline form with labels-->
            <div>&nbsp;</div>
            <button type="submit" class="btn btn-primary mt-2">Filter</button>
            <!--trick to reset a prefilled form to empty-->
            <a href="?" class="btn btn-secondary mt-2">Reset</a>
        </div>
    </form>
    <table class="table">
        {% if resp and resp|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {% for r in resp[0] %}
                <th>{{r}}</th>
                {% endfor %}
            </tr>
        </thead>
        {% for r in resp %}
        <tr>
            {% for v in r.values() %}
            <td>{{v}}</td>
            {% endfor %}
            <td><a href="{{url_for('sample.edit', id=r.get('id'))}}" class="btn btn-secondary btn-sm">Edit</a>
                {# **request.args spreads the key value pairs to be part of the url#}
                {# the idea is to pass it to the next route #}
                <a href="{{url_for('sample.delete', id=r.get('id'), **request.args)}}"
                    class="btn btn-danger btn-sm">x</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <p>No results to show</p>
        {% endif %}
    </table>
</div>
</div>
{% endblock %}

templates/maxmoney.html
{% extends "layout.html" %}

{% block content %}

  <div class="container">
    <h1>Max Money Sent/Received Per Month</h1>
    <!-- <hr>
    {% for month, transactions in transactions_by_month.items() %}
      <h2>{{ month }}</h2>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Transaction ID</th>
            <th>Memo</th>
            <th>Amount</th>
            <th>Sent To/Received From</th>
            <th>Cancel Reason</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {% for transaction in transactions %}
          {% if transaction["AMOUNT"]==max_sent_transactions or transaction["AMOUNT"]==max_received_by_month %}
          <tr>
            <td>{{ transaction["STID"] }}</td>
            <td>{{ transaction["MEMO"] }}</td>
            <td>{{ transaction["AMOUNT"]|float|round(2) }}</td>
            <td>{{ transaction["IDENTIFIER"] if transaction["SSN"] != user_ssn.row["SSN"] else "Sent to {}".format(transaction["IDENTIFIER"]) }}</td>
            <td>{{ transaction["CANCEL_REASON"] }}</td>
            <td>{{ transaction["DATE_TIME"].strftime("%Y-%m-%d %H:%M:%S") }}</td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    {% endfor %} -->
    <hr>
    <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Transaction ID</th>
            <th>Memo</th>
            <th>Amount</th>
            <th>Sent To/Received From</th>
            <th>Cancel Reason</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {% for transaction in max_sent_transactions %}
          
          <tr>
            <td>{{ transaction["STID"] }}</td>
            <td>{{ transaction["MEMO"] }}</td>
            <td>{{ transaction["AMOUNT"]|float|round(2) }}</td>
            <td>{{ transaction["IDENTIFIER"] }}</td>
            <td>{{ transaction["CANCEL_REASON"] }}</td>
            <td>{{ transaction["DATE_TIME"].strftime("%Y-%m-%d %H:%M:%S") }}</td>
          </tr>
          {% endfor %}
          {% for transaction in max_received_transactions %}
          <tr>
            <td>{{ transaction["STID"] }}</td>
            <td>{{ transaction["MEMO"] }}</td>
            <td>{{ transaction["AMOUNT"]|float|round(2) }}</td>
            <td>{{ transaction["IDENTIFIER"] }}</td>
            <td>{{ transaction["CANCEL_REASON"] }}</td>
            <td>{{ transaction["DATE_TIME"].strftime("%Y-%m-%d %H:%M:%S") }}</td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock %}

templates/nav.html
{% from "_dropdown_nav.html" import dropdown_nav %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Wallet Payment Network</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.landing_page')}}">Home</a>
                </li>
                {% set samples = [
                    ("main_menu.account_info", "Account Info"),
                    ("main_menu.send", "Send Money"),
                    ("main_menu.request_money", "Request Money"),
                    ("main_menu.monthly_statements", "Monthly Statements"),
                    ("main_menu.search_transactions", "Search Transactions")
                    ] %}
                    {{dropdown_nav("Main Menu", samples)}}
                {% set functions = [
                        ("account.modify", "Modify Personal Details"),
                        ("account.email", "Add/remove email"),
                        ("account.phone", "Add/remove phone"),
                        ("account.bank","Add/remove bank") 
                        ] %}
                        {{dropdown_nav("Account Functions", functions)}}
                {% set statementss = [
                    ("main_menu.totalamount", "Total money sent per month"),
                    ("main_menu.avgmoney", "Average money sent per month"),
                    ("main_menu.maxmoney", "Maximum money sent per month"),
                    ] %}
                    {{dropdown_nav("Statement Functions", statementss)}}
                
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>